package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"silenttunnel/internal/config"
)

const systemdUnitTmpl = `# Silent Tunnel — generated by 'silent install'
[Unit]
Description=Silent Tunnel (%s)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=%s %s
Restart=always
RestartSec=5
LimitNOFILE=1048576
# Nodes (abroad) should dial out even while the box is unattended.
KillSignal=SIGINT
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
`

// cmdInstall registers a systemd service for the configured role.
func cmdInstall(args []string) int {
	if runtime.GOOS == "windows" {
		fmt.Println("روی ویندوز systemd نیست. دو راه دارید:")
		fmt.Println("  1) اجرای دستی در ترمینال:  silent.exe hub   یا   silent.exe node")
		fmt.Println(`  2) سرویس ویندوز (NSSM):  nssm install SilentTunnel "C:\path\silent.exe" hub`)
		fmt.Println(`     یا اجرای خودکار موقع بوت:  schtasks /Create /SC ONSTART /TN SilentTunnel /RU SYSTEM /TR "C:\path\silent.exe hub"`)
		return 1
	}
	if os.Geteuid() != 0 {
		errf("برای نصب سرویس root لازم است (sudo silent install)")
		return 1
	}

	role, _ := detectRole()
	if role == "" {
		errf("کانفیگی پیدا نشد — اول setup-hub یا setup-node را اجرا کن")
		return 1
	}

	self, err := os.Executable()
	if err != nil {
		errf("مسیر باینری: %v", err)
		return 1
	}
	self, _ = filepath.Abs(self)
	target := "/usr/local/bin/silent"
	if self != target {
		b, err := os.ReadFile(self)
		if err != nil {
			errf("کپی باینری: %v", err)
			return 1
		}
		if err := os.WriteFile(target, b, 0o755); err != nil {
			errf("نوشتن %s: %v (root هستی؟)", target, err)
			return 1
		}
	}

	unit := fmt.Sprintf(systemdUnitTmpl, role, target, role)
	unitPath := fmt.Sprintf("/etc/systemd/system/silent-%s.service", role)
	if err := os.WriteFile(unitPath, []byte(unit), 0o644); err != nil {
		errf("نوشتن unit: %v", err)
		return 1
	}
	if code, err := runShell("systemctl daemon-reload"); err != nil || code != 0 {
		errf("systemctl daemon-reload ناموفق: %v", err)
		return 1
	}
	if code, err := runShell(fmt.Sprintf("systemctl enable --now silent-%s", role)); err != nil || code != 0 {
		errf("فعال‌سازی سرویس ناموفق: %v", err)
		return 1
	}
	okf("سرویس silent-%s نصب و فعال شد", role)
	tipf("وضعیت:  systemctl status silent-%s", role)
	tipf("لاگ:    journalctl -u silent-%s -f", role)
	return 0
}

// cmdUninstall removes the service and (optionally) the configuration.
func cmdUninstall(args []string) int {
	if runtime.GOOS == "windows" {
		fmt.Println(`روی ویندوز:  nssm remove SilentTunnel confirm  یا  schtasks /Delete /TN SilentTunnel /F`)
		return 0
	}
	removed := false
	for _, role := range []string{"hub", "node"} {
		unit := fmt.Sprintf("/etc/systemd/system/silent-%s.service", role)
		if _, err := os.Stat(unit); err != nil {
			continue
		}
		_, _ = runShell(fmt.Sprintf("systemctl disable --now silent-%s", role))
		if err := os.Remove(unit); err == nil {
			removed = true
			okf("سرویس silent-%s حذف شد", role)
		}
	}
	if removed {
		_, _ = runShell("systemctl daemon-reload")
	}
	if os.Geteuid() == 0 {
		_ = os.Remove("/usr/local/bin/silent")
	}
	if confirmWipe() {
		for _, p := range []string{config.HubPath(), config.NodePath()} {
			if err := os.Remove(p); err == nil {
				okf("حذف شد: %s", p)
			}
		}
	}
	tipf("تمام شد")
	return 0
}

func confirmWipe() bool {
	if !isTTY() {
		return false
	}
	v, err := Confirm("فایل‌های کانفیگ و توکن هم حذف شوند؟", false)
	return err == nil && v
}

// detectRole finds which role this server is configured for.
func detectRole() (role, cfgPath string) {
	if _, err := os.Stat(config.HubPath()); err == nil {
		return "hub", config.HubPath()
	}
	if _, err := os.Stat(config.NodePath()); err == nil {
		return "node", config.NodePath()
	}
	return "", ""
}

// runShell executes a command, streaming its output to ours.
func runShell(cmdline string) (int, error) {
	parts := strings.Fields(cmdline)
	if len(parts) == 0 {
		return 1, fmt.Errorf("empty command")
	}
	return shExec(parts[0], parts[1:]...)
}
